#run `yarn format` and `yarn lint` on merge to master and deploy the dist folder to github pages
name: formatting and linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  verify:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"
      - run: yarn install
      - run: yarn format
      - run: yarn lint
      - run: yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
